### ISSUE TITLE
Upgrade standardrb support

### ISSUE THREAD

**Issue by amkisko** [qltysh/codeclimate#1125]
Hey!

It seems that ruby `standard` gem support is outdated. Is possible by any chance to update it?

Recent error from the service:
```
/usr/local/bundle/gems/rubocop-ast-0.3.0/lib/rubocop/ast/processed_source.rb:222:in `parser_class': RuboCop found unknown Ruby version: 3.3 (ArgumentError)
	from /usr/local/bundle/gems/rubocop-ast-0.3.0/lib/rubocop/ast/processed_source.rb:231:in `create_parser'
	from /usr/local/bundle/gems/rubocop-ast-0.3.0/lib/rubocop/ast/processed_source.rb:184:in `parse'
	from /usr/local/bundle/gems/rubocop-ast-0.3.0/lib/rubocop/ast/processed_source.rb:34:in `initialize'
	from /usr/local/bundle/gems/rubocop-ast-0.3.0/lib/rubocop/ast/processed_source.rb:19:in `new'
	from /usr/local/bundle/gems/rubocop-ast-0.3.0/lib/rubocop/ast/processed_source.rb:19:in `from_file'
	from /usr/src/app/lib/cc/engine/source_file.rb:25:in `processed_source'
	from /usr/src/app/lib/cc/engine/source_file.rb:12:in `inspect'
	from /usr/src/app/lib/cc/engine/standard.rb:31:in `block (2 levels) in run'
	from /usr/src/app/lib/cc/engine/standard.rb:25:in `each'
	from /usr/src/app/lib/cc/engine/standard.rb:25:in `block in run'
	from /usr/src/app/lib/cc/engine/standard.rb:24:in `chdir'
	from /usr/src/app/lib/cc/engine/standard.rb:24:in `run'
	from /usr/src/app/bin/codeclimate-standard:15:in `<main>'
```

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
