### ISSUE TITLE
ERROR: lxml.etree.XMLSyntaxError: internal error: Huge input lookup

### ISSUE THREAD

**Issue by frakman1** [qltysh/codeclimate#975]
I get this error when analyzing a project with 3694 files. 

```bash
CONTAINER_TIMEOUT_SECONDS=6480000 CODECLIMATE_DEBUG=1 CODECLIMATE_CODE="$PWD" codeclimate analyze -f html > report.html
```

```bash
D, [2020-08-19T00:38:05.135210 #1] DEBUG -- : engine stderr: [cppcheck] analyzing 3694 files
D, [2020-08-19T00:38:05.135292 #1] DEBUG -- : engine stderr: [cppcheck] command: ['cppcheck', '--enable=all', '--language=c++', '--std=c++11', '--inconclusive', '--xml', '--xml-version=2', '--file-list=/tmp/tmpynzkothz']
D, [2020-08-19T00:38:05.136687 #1] DEBUG -- : engine stderr: Traceback (most recent call last):
D, [2020-08-19T00:38:05.136761 #1] DEBUG -- : engine stderr:   File "/usr/src/app/bin/codeclimate-cppcheck", line 12, in <module>
D, [2020-08-19T00:38:05.136809 #1] DEBUG -- : engine stderr:     Runner().run()
D, [2020-08-19T00:38:05.136896 #1] DEBUG -- : engine stderr:   File "/usr/src/app/lib/runner.py", line 40, in run
D, [2020-08-19T00:38:05.136969 #1] DEBUG -- : engine stderr:     issues = self._parse_results(results)
D, [2020-08-19T00:38:05.137021 #1] DEBUG -- : engine stderr:   File "/usr/src/app/lib/runner.py", line 81, in _parse_results
D, [2020-08-19T00:38:05.137123 #1] DEBUG -- : engine stderr:     root = etree.fromstring(results)
D, [2020-08-19T00:38:05.137208 #1] DEBUG -- : engine stderr:   File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
D, [2020-08-19T00:38:05.137277 #1] DEBUG -- : engine stderr:   File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
D, [2020-08-19T00:38:05.137504 #1] DEBUG -- : engine stderr:   File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
D, [2020-08-19T00:38:05.137591 #1] DEBUG -- : engine stderr:   File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
D, [2020-08-19T00:38:05.137628 #1] DEBUG -- : engine stderr:   File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
D, [2020-08-19T00:38:05.137714 #1] DEBUG -- : engine stderr:   File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
D, [2020-08-19T00:38:05.137858 #1] DEBUG -- : engine stderr:   File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
D, [2020-08-19T00:38:05.137953 #1] DEBUG -- : engine stderr:   File "<string>", line 157925
D, [2020-08-19T00:38:05.138014 #1] DEBUG -- : engine stderr: lxml.etree.XMLSyntaxError: internal error: Huge input lookup, line 157925, column 287
I, [2020-08-19T00:38:05.691449 #1]  INFO -- : finished engine cppcheck
error: (CC::CLI::Analyze::EngineFailure) engine cppcheck failed with status 1 and stderr
```

I [checked](https://github.com/antiagainst/codeclimate-cppcheck/issues/39) first with the [cppcheck](https://github.com/antiagainst/codeclimate-cppcheck) team and they said:

> It seems that the error is not in cppcheck. We don't use lxml internally. Instead we use xml module from the standard library in [addons](https://github.com/danmar/cppcheck/blob/6446790d48102dc68f91b14a4e025031c10b6f09/addons/cppcheckdata.py#L13). So, I suppose this is a codeclimate issue.

**Comment by brynary** [comment]
Hello -- Thank you for this GitHub issue.

We are going to be releasing a new version of our code quality CLI shortly, and so I am in the process of closing all open GitHub issues in preparation for that. We will be in touch soon and would be happy to hear from you on any feedback you have on the new CLI when it is available later this month.
